{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
metadata:
  labels:
    {{ include "wave.labels" . | nindent 4 }}
  name: {{ include "wave.serviceAccountName" . }}
{{- end }}
